import Foundation

class PlantUMLContext {
    private(set) var configuration: Configuration

    // lookup the unique name (generated by SwiftPlantUML) for a given element
    var uniqueNameForElement: [SyntaxStructure: String] = [:]

    var uniqElementNames: [String] = []
    var uniqElementAndTypes: [String: String] = [:]
    // var style: [String: String] = [:]
    private(set) var connections: [String] = []
    private(set) var extnConnections: [String] = []
    /// 跨 group 且有关系的分组对（用于全关时的聚合线），格式 `"GroupA" -> "GroupB"`
    private(set) var interGroupPairs: Set<String> = []

    private let linkTypeInheritance = "<|--"
    private let linkTypeRealize = "<|.."
    private let linkTypeDependency = "<.."
    private let linkTypeAssociation = "-->"
    private let linkTypeComposition = "*--"
    private let linkTypeGeneric = "--"

    /// 类型名 → 分组名 的映射（由 PlantUMLScript 注入）
    var groupForTypeName: [String: String] = [:]

    init(configuration: Configuration = .default) {
        self.configuration = configuration
    }

    var index = 0

    /// 判断两个类型是否跨 group（均须已分组）。
    private func isCrossGroup(_ fromName: String, _ toName: String) -> Bool {
        guard let fromGroup = groupForTypeName[fromName], let toGroup = groupForTypeName[toName] else { return false }
        return fromGroup != toGroup
    }

    /// 跨 group 裁剪：返回该关系类型是否允许跨组绘制；不允许时按 singleLine 规则记录聚合对。
    private func shouldAllowCrossGroup(fromName: String, toName: String, kind: RelationshipKind) -> Bool {
        guard isCrossGroup(fromName, toName) else { return true }
        let crossGroup = configuration.groupSettings.crossGroupRelationships
        if crossGroup.singleLine.allGroups {
            // 所有跨 group 关系都聚合为 group 间单行链接，不绘制逐条边
            interGroupPairs.insert(groupPairKey(fromName, toName))
            return false
        }
        if crossGroup.allows(kind) {
            return true
        }
        if crossGroup.singleLine.excludeSameGroup {
            // 禁止的跨组关系聚合并为单行，同一个 group 内不受影响
            interGroupPairs.insert(groupPairKey(fromName, toName))
        }
        return false
    }

    private func groupPairKey(_ a: String, _ b: String) -> String {
        let ga = groupForTypeName[a] ?? "?"
        let gb = groupForTypeName[b] ?? "?"
        return ga < gb ? "\(ga)|\(gb)" : "\(gb)|\(ga)"
    }

    func addLinking(item: SyntaxStructure, parent: SyntaxStructure) {
        var linkTo = parent.name?.removeAngleBracketsWithContent() ?? "___"

        // escape names like "@unchecked Sendable" for PlantUML
        if linkTo.starts(with: "@") {
            linkTo = "\"\(linkTo)\""
        }

        let namedConnection = (uniqElementAndTypes[linkTo] != nil) ? "\(uniqElementAndTypes[linkTo] ?? "--ERROR--")" : "inherits"
        var linkTypeKey = item.fullName! + "LinkType"

        // 继承与实现（conforms to）同属 inheritance 类；扩展依赖归 dependency 类
        let kind: RelationshipKind
        if uniqElementAndTypes[linkTo] == "conforms to" {
            linkTypeKey = linkTo + "LinkType"
            kind = .inheritance
        } else if namedConnection == "ext" {
            kind = .dependency
        } else {
            kind = .inheritance
        }

        guard skipLinking(element: parent, basedOn: effectiveExcludes(item: item, kind: kind)) == false else { return }

        let itemName = item.fullName ?? item.name ?? ""
        guard shouldAllowCrossGroup(fromName: itemName, toName: parent.name?.removeAngleBracketsWithContent() ?? "", kind: kind) else { return }

        let connect = "\(linkTo) \(uniqElementAndTypes[linkTypeKey] ?? "--ERROR--") \(item.fullName!)"
        connections.append(connect)
    }

    /// 添加由源码依赖推导出的关联/组合关系线。
    /// - Parameter item: 源类型（用于按命中规则计算排除名单、启用开关与跨组裁剪）
    func addDerivedLinking(from sourceName: String, to targetName: String, kind: RelationshipKind, item: SyntaxStructure) {
        let resolvedRelationships = item.effectiveResolvedRule?.relationships
        guard resolvedRelationships?.isEnabled(kind) ?? configuration.elements.relationships.isEnabled(kind) else { return }
        guard skipLinking(targetName: targetName, basedOn: effectiveExcludes(item: item, kind: kind)) == false else { return }
        guard shouldAllowCrossGroup(fromName: sourceName, toName: targetName, kind: kind) else { return }

        let linkType: String
        switch kind {
        case .composition:
            linkType = linkTypeComposition
        case .association:
            linkType = linkTypeAssociation
        default:
            return
        }

        connections.append("\(sourceName) \(linkType) \(targetName)")
    }

    /// 计算命中规则后的排除名单（继承/关联/聚合/组合/依赖）。
    ///
    /// 元素级 exclude 语义为「过滤该类型及其全部信息（属性、方法、关系）」，
    /// 因此链接目标命中元素级 exclude 时也裁剪该条连线（否则被排除类型仍以幽灵节点残留）；
    /// 关系级 exclude 在此基础上追加过滤指定关系类型的目标。
    /// 全局与 group 级已在 `ResolvedRule.resolve` 合并（含 `$(inherit)` token 解析）。
    private func effectiveExcludes(item: SyntaxStructure, kind: RelationshipKind) -> [String]? {
        let elementOptions = item.effectiveResolvedRule?.elements ?? configuration.elements
        let relationshipExcludes = item.effectiveResolvedRule?.relationships.exclude(for: kind) ?? configuration.elements.relationships.exclude(for: kind)
        return elementOptions.exclude + (relationshipExcludes ?? [])
    }

    private func skipLinking(element: SyntaxStructure, basedOn excludeElements: [String]?) -> Bool {
        guard let elementName = element.name else { return false }
        guard let excludedElements = excludeElements else { return false }
        return !excludedElements.filter { elementName.isMatching(searchPattern: $0) }.isEmpty
    }

    private func skipLinking(targetName: String, basedOn excludeElements: [String]?) -> Bool {
        guard let excludedElements = excludeElements else { return false }
        return !excludedElements.filter { targetName.isMatching(searchPattern: $0) }.isEmpty
    }

    func uniqName(item: SyntaxStructure, relationship: String) -> String {
        guard let name = item.fullName else { return "" }
        var newName = name
        let linkTypeKey = name + "LinkType"
        if uniqElementNames.contains(name) {
            newName += "\(index)"
            index += 1
            if item.kind == ElementKind.extension,
               uniqueNameForElement.keys.first(where: { $0.name == name && $0.kind != .extension }) != nil
            {
                var connect = "\(name) \(linkTypeDependency) \(newName)"
                connect += " : \(relationship)"
                extnConnections.append(connect) // "aPublicStruct <.. aPublicStruct0 : ext"
            }
        } else {
            uniqElementNames.append(name)
            uniqElementAndTypes[name] = relationship

            if relationship == "inherits" {
                uniqElementAndTypes[linkTypeKey] = linkTypeInheritance
            } else if relationship == "conforms to" {
                uniqElementAndTypes[linkTypeKey] = linkTypeRealize
            } else if relationship == "ext" {
                uniqElementAndTypes[linkTypeKey] = linkTypeDependency
            } else {
                uniqElementAndTypes[linkTypeKey] = linkTypeGeneric
            }
        }
        uniqueNameForElement[item] = newName
        return newName
    }

    func collectNestedTypeConnections(items: [SyntaxStructure]) {
        for item in items where item.parent != nil {
            guard let name = uniqueNameForElement[item],
                  let parentName = uniqueNameForElement[item.parent!] ?? item.parent?.name
            else {
                continue
            }
            connections.append("\(parentName) +-- \(name)")
        }
    }

    /// 生成 group 之间的聚合线（按 singleLine 规则汇总的跨组关系对）。
    /// 返回形如 `"GroupA" -- "GroupB"` 的行；被允许的跨组关系照常绘制，不在此列。
    func groupAggregateLines() -> [String] {
        guard configuration.groupSettings.enabledGroups.isEmpty == false, !interGroupPairs.isEmpty else { return [] }
        let lines = interGroupPairs.map { pair -> String in
            let comps = pair.split(separator: "|")
            guard comps.count == 2 else { return pair }
            return "\"\(comps[0])\" -- \"\(comps[1])\""
        }
        return Array(lines).sorted()
    }
}
